### ISSUE TITLE
TM2020 Stunt

### ISSUE THREAD

**Issue by forsureitsme** [ThaumicTom/gbx.js#6]
Nadeo added Stunt to Trackmania2020, adding the Trackmania\TM_Stunt play mode to the list of play modes used in *.Map.Gbx files.

Looking at the code superficially, adding "Stunt" to [the list of play mode enums](https://github.com/thaumictom/gbx-ts/blob/addd4a3aee0ee74706a95d4d979785c88a2bf212/src/types.ts#L78C1-L87C1) should suffice, since the target scores are stored in the medals.

_I tried creating a fork to test this for a pull request, but couldn't get it working._

**Comment by BigBang1112** [comment]
`PlayMode` will likely continue being `Script` in this case. It's how Nadeo handles modes nowadays. The other options are relevant in TMUF and older games.

The `mapType` is now the primary source of knowing the mode.

**Comment by forsureitsme** [comment]
My bad, I really don't know how I got them mixed up.
